apiVersion: v1 
kind: Pod 
metadata:
  name: robo-ecommerce-pod-example
  namespace: roboshop-ns 
spec:
  contianers:
    - image: anusocial123/ecommerce-web:latest
      name: web-container
      ports:
        - containerPort: 80  
